"""DomainPlugin — the pluggable seam between Aletheia's reasoning loop and a
concrete scientific task. Phase 1 ships one: materials band-gap regression.

A plugin turns a *design* (the concrete spec the agent commits to) + a *data spec*
(a resolved ``DataAsset``) into metrics + artifacts, without the orchestrator ever
touching raw compute in its own context — the compute adapter runs the plugin in a
subprocess and the plugin reports back through this contract.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


@dataclass
class ExperimentResult:
    """What a single train/evaluate run produces. JSON-serializable via ``to_dict``."""

    metrics: dict[str, float] = field(default_factory=dict)  # {"mae":.., "r2":.., "rmse":..}
    artifacts: list[dict[str, Any]] = field(default_factory=list)  # [{kind, uri, ...}]
    info: dict[str, Any] = field(default_factory=dict)  # n_train/n_test/feature_count/model/...

    def to_dict(self) -> dict[str, Any]:
        return {"metrics": self.metrics, "artifacts": self.artifacts, "info": self.info}


class DomainPlugin(ABC):
    """Contract every domain implements. Steps are separable so they can be unit
    tested offline (featurize/train on a tiny in-memory frame) and also composed by
    ``run_experiment`` for subprocess execution."""

    name: str = "base"

    @abstractmethod
    def load_data(self, data_spec: dict[str, Any]) -> Any:
        """Resolve a data spec (source benchmark|upload|api) to a DataFrame."""

    @abstractmethod
    def featurize(self, df: Any, design: dict[str, Any]) -> tuple[Any, Any, list[str]]:
        """Return ``(X, y, feature_names)`` for the given design."""

    @abstractmethod
    def train_evaluate(
        self, X: Any, y: Any, design: dict[str, Any], workdir: Path
    ) -> ExperimentResult:
        """Fit the design's model, score on a held-out split, save artifacts."""

    @abstractmethod
    def baselines(self) -> list[dict[str, Any]]:
        """Candidate model/feature specs the agent can choose among / compare."""

    def run_experiment(
        self, design: dict[str, Any], data_spec: dict[str, Any], workdir: Path
    ) -> ExperimentResult:
        """End-to-end load -> featurize -> train/evaluate. Used by the subprocess
        training script generated by the compute adapter."""
        df = self.load_data(data_spec)
        X, y, feature_names = self.featurize(df, design)
        result = self.train_evaluate(X, y, design, Path(workdir))
        result.info.setdefault("feature_count", len(feature_names))
        result.info.setdefault("n_rows", int(getattr(df, "shape", [0])[0]))
        return result
