"""Add the immutable F11 Quest/Program/Campaign scientific graph.

Revision ID: 20260817_0013
Revises: 20260817_0012
Create Date: 2026-08-17 02:46:13.287935
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "20260817_0013"
down_revision: str | None = "20260817_0012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "research_graph_nodes",
        sa.Column("node_id", sa.String(length=96), nullable=False),
        sa.Column("quest_id", sa.String(length=96), nullable=False),
        sa.Column("parent_node_id", sa.String(length=96), nullable=True),
        sa.Column("node_type", sa.String(length=16), nullable=False),
        sa.Column("identity_key", sa.String(length=128), nullable=False),
        sa.Column("spec_sha256", sa.String(length=64), nullable=False),
        sa.Column("spec_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("current_state", sa.String(length=24), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(node_type = 'quest' AND parent_node_id IS NULL AND quest_id = node_id) OR (node_type IN ('program','campaign') AND parent_node_id IS NOT NULL AND quest_id <> node_id)",
            name="ck_research_graph_nodes_hierarchy_shape",
        ),
        sa.CheckConstraint(
            "node_type IN ('quest','program','campaign')", name="ck_research_graph_nodes_type"
        ),
        sa.CheckConstraint("state_version >= 1", name="ck_research_graph_nodes_state_version"),
        sa.ForeignKeyConstraint(
            ["parent_node_id"],
            ["research_graph_nodes.node_id"],
        ),
        sa.ForeignKeyConstraint(
            ["quest_id"],
            ["research_graph_nodes.node_id"],
        ),
        sa.PrimaryKeyConstraint("node_id"),
        sa.UniqueConstraint(
            "quest_id", "node_type", "identity_key", name="uq_research_graph_nodes_scoped_identity"
        ),
    )
    op.create_index(
        op.f("ix_research_graph_nodes_created_at"),
        "research_graph_nodes",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_graph_nodes_created_by"),
        "research_graph_nodes",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_graph_nodes_current_state"),
        "research_graph_nodes",
        ["current_state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_graph_nodes_node_type"),
        "research_graph_nodes",
        ["node_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_graph_nodes_parent_node_id"),
        "research_graph_nodes",
        ["parent_node_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_graph_nodes_quest_id"), "research_graph_nodes", ["quest_id"], unique=False
    )
    op.create_index(
        "ix_research_graph_nodes_quest_type",
        "research_graph_nodes",
        ["quest_id", "node_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_graph_nodes_spec_sha256"),
        "research_graph_nodes",
        ["spec_sha256"],
        unique=False,
    )
    op.create_table(
        "research_budget_allocations",
        sa.Column("allocation_id", sa.String(length=96), nullable=False),
        sa.Column("quest_id", sa.String(length=96), nullable=False),
        sa.Column("scope_node_id", sa.String(length=96), nullable=False),
        sa.Column("parent_allocation_id", sa.String(length=96), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("cap_microunits", sa.BigInteger(), nullable=False),
        sa.Column("policy_sha256", sa.String(length=64), nullable=False),
        sa.Column("policy_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("command_id", sa.String(length=96), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('usd','gpu_hours','agent_sdk_credit','tokens','wall_clock_hours','experiment_count')",
            name="ck_research_budget_allocations_kind",
        ),
        sa.CheckConstraint("cap_microunits > 0", name="ck_research_budget_allocations_cap"),
        sa.ForeignKeyConstraint(
            ["command_id"],
            ["scientific_commands.command_id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_allocation_id"],
            ["research_budget_allocations.allocation_id"],
        ),
        sa.ForeignKeyConstraint(
            ["quest_id"],
            ["research_graph_nodes.node_id"],
        ),
        sa.ForeignKeyConstraint(
            ["scope_node_id"],
            ["research_graph_nodes.node_id"],
        ),
        sa.PrimaryKeyConstraint("allocation_id"),
        sa.UniqueConstraint("command_id", name="uq_research_budget_allocations_command"),
        sa.UniqueConstraint(
            "scope_node_id", "kind", name="uq_research_budget_allocations_scope_kind"
        ),
    )
    op.create_index(
        op.f("ix_research_budget_allocations_command_id"),
        "research_budget_allocations",
        ["command_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_budget_allocations_created_at"),
        "research_budget_allocations",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_budget_allocations_kind"),
        "research_budget_allocations",
        ["kind"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_budget_allocations_parent_allocation_id"),
        "research_budget_allocations",
        ["parent_allocation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_budget_allocations_quest_id"),
        "research_budget_allocations",
        ["quest_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_budget_allocations_scope_node_id"),
        "research_budget_allocations",
        ["scope_node_id"],
        unique=False,
    )
    op.create_table(
        "research_campaign_experiments",
        sa.Column("binding_id", sa.String(length=96), nullable=False),
        sa.Column("quest_id", sa.String(length=96), nullable=False),
        sa.Column("campaign_node_id", sa.String(length=96), nullable=False),
        sa.Column("experiment_id", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("command_id", sa.String(length=96), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["campaign_node_id"],
            ["research_graph_nodes.node_id"],
        ),
        sa.ForeignKeyConstraint(
            ["command_id"],
            ["scientific_commands.command_id"],
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quest_id"],
            ["research_graph_nodes.node_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("binding_id"),
        sa.UniqueConstraint("command_id", name="uq_research_campaign_experiments_command"),
        sa.UniqueConstraint("experiment_id", name="uq_research_campaign_experiments_experiment"),
    )
    op.create_index(
        op.f("ix_research_campaign_experiments_campaign_node_id"),
        "research_campaign_experiments",
        ["campaign_node_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_campaign_experiments_command_id"),
        "research_campaign_experiments",
        ["command_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_campaign_experiments_created_at"),
        "research_campaign_experiments",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_campaign_experiments_experiment_id"),
        "research_campaign_experiments",
        ["experiment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_campaign_experiments_quest_id"),
        "research_campaign_experiments",
        ["quest_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_campaign_experiments_run_id"),
        "research_campaign_experiments",
        ["run_id"],
        unique=False,
    )
    op.create_table(
        "research_campaign_runs",
        sa.Column("binding_id", sa.String(length=96), nullable=False),
        sa.Column("quest_id", sa.String(length=96), nullable=False),
        sa.Column("campaign_node_id", sa.String(length=96), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("command_id", sa.String(length=96), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["campaign_node_id"],
            ["research_graph_nodes.node_id"],
        ),
        sa.ForeignKeyConstraint(
            ["command_id"],
            ["scientific_commands.command_id"],
        ),
        sa.ForeignKeyConstraint(
            ["quest_id"],
            ["research_graph_nodes.node_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("binding_id"),
        sa.UniqueConstraint("command_id", name="uq_research_campaign_runs_command"),
        sa.UniqueConstraint("run_id", name="uq_research_campaign_runs_run"),
    )
    op.create_index(
        op.f("ix_research_campaign_runs_campaign_node_id"),
        "research_campaign_runs",
        ["campaign_node_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_campaign_runs_command_id"),
        "research_campaign_runs",
        ["command_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_campaign_runs_created_at"),
        "research_campaign_runs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_campaign_runs_quest_id"),
        "research_campaign_runs",
        ["quest_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_campaign_runs_run_id"), "research_campaign_runs", ["run_id"], unique=False
    )
    op.create_table(
        "research_data_role_allocations",
        sa.Column("allocation_id", sa.String(length=96), nullable=False),
        sa.Column("quest_id", sa.String(length=96), nullable=False),
        sa.Column("scope_node_id", sa.String(length=96), nullable=False),
        sa.Column("data_asset_id", sa.String(length=32), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("exclusive", sa.Boolean(), nullable=False),
        sa.Column("policy_sha256", sa.String(length=64), nullable=False),
        sa.Column("policy_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("command_id", sa.String(length=96), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('exploration','training','confirmation','external_validation','replication','safety')",
            name="ck_research_data_role_allocations_role",
        ),
        sa.ForeignKeyConstraint(
            ["command_id"],
            ["scientific_commands.command_id"],
        ),
        sa.ForeignKeyConstraint(
            ["data_asset_id"],
            ["data_assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quest_id"],
            ["research_graph_nodes.node_id"],
        ),
        sa.ForeignKeyConstraint(
            ["scope_node_id"],
            ["research_graph_nodes.node_id"],
        ),
        sa.PrimaryKeyConstraint("allocation_id"),
        sa.UniqueConstraint("command_id", name="uq_research_data_role_allocations_command"),
        sa.UniqueConstraint(
            "scope_node_id",
            "data_asset_id",
            "role",
            name="uq_research_data_role_allocations_scope_asset_role",
        ),
    )
    op.create_index(
        op.f("ix_research_data_role_allocations_command_id"),
        "research_data_role_allocations",
        ["command_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_data_role_allocations_created_at"),
        "research_data_role_allocations",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_data_role_allocations_data_asset_id"),
        "research_data_role_allocations",
        ["data_asset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_data_role_allocations_quest_id"),
        "research_data_role_allocations",
        ["quest_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_data_role_allocations_role"),
        "research_data_role_allocations",
        ["role"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_data_role_allocations_scope_node_id"),
        "research_data_role_allocations",
        ["scope_node_id"],
        unique=False,
    )
    op.create_table(
        "research_graph_dependencies",
        sa.Column("edge_id", sa.String(length=96), nullable=False),
        sa.Column("quest_id", sa.String(length=96), nullable=False),
        sa.Column("node_id", sa.String(length=96), nullable=False),
        sa.Column("dependency_node_id", sa.String(length=96), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("command_id", sa.String(length=96), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "node_id <> dependency_node_id", name="ck_research_graph_dependencies_not_self"
        ),
        sa.ForeignKeyConstraint(
            ["command_id"],
            ["scientific_commands.command_id"],
        ),
        sa.ForeignKeyConstraint(
            ["dependency_node_id"],
            ["research_graph_nodes.node_id"],
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["research_graph_nodes.node_id"],
        ),
        sa.ForeignKeyConstraint(
            ["quest_id"],
            ["research_graph_nodes.node_id"],
        ),
        sa.PrimaryKeyConstraint("edge_id"),
        sa.UniqueConstraint("command_id", name="uq_research_graph_dependencies_command"),
        sa.UniqueConstraint(
            "node_id", "dependency_node_id", name="uq_research_graph_dependencies_pair"
        ),
    )
    op.create_index(
        op.f("ix_research_graph_dependencies_command_id"),
        "research_graph_dependencies",
        ["command_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_graph_dependencies_created_at"),
        "research_graph_dependencies",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_graph_dependencies_dependency_node_id"),
        "research_graph_dependencies",
        ["dependency_node_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_graph_dependencies_node_id"),
        "research_graph_dependencies",
        ["node_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_graph_dependencies_quest_id"),
        "research_graph_dependencies",
        ["quest_id"],
        unique=False,
    )
    op.create_table(
        "research_graph_transitions",
        sa.Column("transition_id", sa.String(length=96), nullable=False),
        sa.Column("node_id", sa.String(length=96), nullable=False),
        sa.Column("command_id", sa.String(length=96), nullable=False),
        sa.Column("from_state", sa.String(length=24), nullable=True),
        sa.Column("to_state", sa.String(length=24), nullable=False),
        sa.Column("from_version", sa.Integer(), nullable=False),
        sa.Column("to_version", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("principal", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(from_version = 0 AND from_state IS NULL) OR (from_version >= 1 AND from_state IS NOT NULL)",
            name="ck_research_graph_transitions_source_shape",
        ),
        sa.CheckConstraint(
            "to_version = from_version + 1", name="ck_research_graph_transitions_version_step"
        ),
        sa.ForeignKeyConstraint(
            ["command_id"],
            ["scientific_commands.command_id"],
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["research_graph_nodes.node_id"],
        ),
        sa.PrimaryKeyConstraint("transition_id"),
        sa.UniqueConstraint("command_id", name="uq_research_graph_transitions_command"),
        sa.UniqueConstraint(
            "node_id", "to_version", name="uq_research_graph_transitions_node_version"
        ),
    )
    op.create_index(
        op.f("ix_research_graph_transitions_command_id"),
        "research_graph_transitions",
        ["command_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_graph_transitions_created_at"),
        "research_graph_transitions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_graph_transitions_node_id"),
        "research_graph_transitions",
        ["node_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_graph_transitions_principal"),
        "research_graph_transitions",
        ["principal"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_graph_transitions_to_state"),
        "research_graph_transitions",
        ["to_state"],
        unique=False,
    )
    op.create_table(
        "research_program_questions",
        sa.Column("binding_id", sa.String(length=96), nullable=False),
        sa.Column("quest_id", sa.String(length=96), nullable=False),
        sa.Column("program_node_id", sa.String(length=96), nullable=False),
        sa.Column("question_sha256", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("command_id", sa.String(length=96), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["command_id"],
            ["scientific_commands.command_id"],
        ),
        sa.ForeignKeyConstraint(
            ["program_node_id"],
            ["research_graph_nodes.node_id"],
        ),
        sa.ForeignKeyConstraint(
            ["quest_id"],
            ["research_graph_nodes.node_id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_sha256"],
            ["epistemic_research_questions.question_sha256"],
        ),
        sa.PrimaryKeyConstraint("binding_id"),
        sa.UniqueConstraint("command_id", name="uq_research_program_questions_command"),
        sa.UniqueConstraint(
            "program_node_id", "question_sha256", name="uq_research_program_questions_pair"
        ),
    )
    op.create_index(
        op.f("ix_research_program_questions_command_id"),
        "research_program_questions",
        ["command_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_program_questions_created_at"),
        "research_program_questions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_program_questions_program_node_id"),
        "research_program_questions",
        ["program_node_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_program_questions_quest_id"),
        "research_program_questions",
        ["quest_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_program_questions_question_sha256"),
        "research_program_questions",
        ["question_sha256"],
        unique=False,
    )
    op.create_table(
        "research_scientific_families",
        sa.Column("family_id", sa.String(length=96), nullable=False),
        sa.Column("quest_id", sa.String(length=96), nullable=False),
        sa.Column("program_node_id", sa.String(length=96), nullable=False),
        sa.Column("family_key", sa.String(length=64), nullable=False),
        sa.Column("semantic_sha256", sa.String(length=64), nullable=False),
        sa.Column("spec_sha256", sa.String(length=64), nullable=False),
        sa.Column("spec_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("command_id", sa.String(length=96), nullable=False),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["command_id"],
            ["scientific_commands.command_id"],
        ),
        sa.ForeignKeyConstraint(
            ["program_node_id"],
            ["research_graph_nodes.node_id"],
        ),
        sa.ForeignKeyConstraint(
            ["quest_id"],
            ["research_graph_nodes.node_id"],
        ),
        sa.PrimaryKeyConstraint("family_id"),
        sa.UniqueConstraint("command_id", name="uq_research_scientific_families_command"),
        sa.UniqueConstraint(
            "program_node_id", "family_key", name="uq_research_scientific_families_program_key"
        ),
    )
    op.create_index(
        op.f("ix_research_scientific_families_command_id"),
        "research_scientific_families",
        ["command_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_scientific_families_created_at"),
        "research_scientific_families",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_scientific_families_created_by"),
        "research_scientific_families",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_scientific_families_family_key"),
        "research_scientific_families",
        ["family_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_scientific_families_program_node_id"),
        "research_scientific_families",
        ["program_node_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_scientific_families_quest_id"),
        "research_scientific_families",
        ["quest_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_scientific_families_semantic_sha256"),
        "research_scientific_families",
        ["semantic_sha256"],
        unique=False,
    )
    op.create_table(
        "research_campaign_families",
        sa.Column("campaign_node_id", sa.String(length=96), nullable=False),
        sa.Column("family_id", sa.String(length=96), nullable=False),
        sa.Column("command_id", sa.String(length=96), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["campaign_node_id"],
            ["research_graph_nodes.node_id"],
        ),
        sa.ForeignKeyConstraint(
            ["command_id"],
            ["scientific_commands.command_id"],
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["research_scientific_families.family_id"],
        ),
        sa.PrimaryKeyConstraint("campaign_node_id"),
        sa.UniqueConstraint("command_id", name="uq_research_campaign_families_command"),
    )
    op.create_index(
        op.f("ix_research_campaign_families_command_id"),
        "research_campaign_families",
        ["command_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_campaign_families_family_id"),
        "research_campaign_families",
        ["family_id"],
        unique=False,
    )
    op.add_column(
        "budget_events",
        sa.Column("research_budget_allocation_id", sa.String(length=96), nullable=True),
    )
    op.create_index(
        op.f("ix_budget_events_research_budget_allocation_id"),
        "budget_events",
        ["research_budget_allocation_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_budget_events_research_budget_allocation",
        "budget_events",
        "research_budget_allocations",
        ["research_budget_allocation_id"],
        ["allocation_id"],
    )
    op.add_column(
        "hypothesis_attempts", sa.Column("research_family_id", sa.String(length=96), nullable=True)
    )
    op.create_index(
        op.f("ix_hypothesis_attempts_research_family_id"),
        "hypothesis_attempts",
        ["research_family_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_hypothesis_attempts_research_family",
        "hypothesis_attempts",
        "research_scientific_families",
        ["research_family_id"],
        ["family_id"],
    )
    op.alter_column(
        "scientific_commands", "run_id", existing_type=sa.VARCHAR(length=32), nullable=True
    )
    op.execute(
        """
        CREATE FUNCTION aletheia_validate_research_graph_node()
        RETURNS trigger AS $$
        DECLARE
          parent_type text;
          parent_quest text;
        BEGIN
          IF NEW.node_type = 'quest' THEN
            IF NEW.parent_node_id IS NOT NULL OR NEW.quest_id <> NEW.node_id THEN
              RAISE EXCEPTION 'quest must be its own root identity';
            END IF;
            RETURN NEW;
          END IF;

          SELECT node_type, quest_id INTO parent_type, parent_quest
          FROM research_graph_nodes WHERE node_id = NEW.parent_node_id;
          IF NOT FOUND THEN
            RAISE EXCEPTION 'research graph parent is missing';
          END IF;
          IF parent_quest <> NEW.quest_id THEN
            RAISE EXCEPTION 'research graph child cannot cross quests';
          END IF;
          IF NEW.node_type = 'program' AND parent_type <> 'quest' THEN
            RAISE EXCEPTION 'program parent must be a quest';
          END IF;
          IF NEW.node_type = 'campaign' AND parent_type <> 'program' THEN
            RAISE EXCEPTION 'campaign parent must be a program';
          END IF;
          RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_research_graph_node_shape
        BEFORE INSERT ON research_graph_nodes
        FOR EACH ROW EXECUTE FUNCTION aletheia_validate_research_graph_node()
        """
    )
    op.execute(
        """
        CREATE FUNCTION aletheia_enforce_research_graph_node_transition()
        RETURNS trigger AS $$
        DECLARE
          allowed boolean := false;
        BEGIN
          IF TG_OP = 'DELETE' THEN
            RAISE EXCEPTION 'research graph node cannot be deleted';
          END IF;
          IF OLD.node_id IS DISTINCT FROM NEW.node_id
             OR OLD.quest_id IS DISTINCT FROM NEW.quest_id
             OR OLD.parent_node_id IS DISTINCT FROM NEW.parent_node_id
             OR OLD.node_type IS DISTINCT FROM NEW.node_type
             OR OLD.identity_key IS DISTINCT FROM NEW.identity_key
             OR OLD.spec_sha256 IS DISTINCT FROM NEW.spec_sha256
             OR OLD.spec_json IS DISTINCT FROM NEW.spec_json
             OR OLD.created_by IS DISTINCT FROM NEW.created_by
             OR OLD.created_at IS DISTINCT FROM NEW.created_at THEN
            RAISE EXCEPTION 'research graph node identity/spec is immutable';
          END IF;
          IF NEW.state_version <> OLD.state_version + 1
             OR NEW.current_state IS NOT DISTINCT FROM OLD.current_state
             OR NEW.updated_at < OLD.updated_at THEN
            RAISE EXCEPTION 'research graph state version is not monotonic';
          END IF;

          allowed := CASE OLD.node_type
            WHEN 'quest' THEN
              (OLD.current_state = 'draft' AND NEW.current_state = 'active') OR
              (OLD.current_state = 'active' AND NEW.current_state IN ('paused','completed')) OR
              (OLD.current_state = 'paused' AND NEW.current_state IN ('active','completed')) OR
              (OLD.current_state = 'completed' AND NEW.current_state = 'archived')
            WHEN 'program' THEN
              (OLD.current_state = 'proposed' AND NEW.current_state IN ('active','stopped')) OR
              (OLD.current_state = 'active' AND NEW.current_state IN ('paused','stopped','completed')) OR
              (OLD.current_state = 'paused' AND NEW.current_state IN ('active','stopped')) OR
              (OLD.current_state IN ('stopped','completed') AND NEW.current_state = 'archived')
            WHEN 'campaign' THEN
              (OLD.current_state = 'planned' AND NEW.current_state IN ('active','stopped')) OR
              (OLD.current_state = 'active' AND NEW.current_state IN ('paused','stopped','completed','failed')) OR
              (OLD.current_state = 'paused' AND NEW.current_state IN ('active','stopped','failed')) OR
              (OLD.current_state IN ('stopped','completed','failed') AND NEW.current_state = 'archived')
            ELSE false
          END;
          IF NOT allowed THEN
            RAISE EXCEPTION 'invalid research graph lifecycle transition';
          END IF;
          RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_research_graph_node_transition
        BEFORE UPDATE OR DELETE ON research_graph_nodes
        FOR EACH ROW EXECUTE FUNCTION aletheia_enforce_research_graph_node_transition()
        """
    )
    op.execute(
        """
        CREATE FUNCTION aletheia_validate_research_dependency()
        RETURNS trigger AS $$
        DECLARE
          left_quest text;
          right_quest text;
          left_type text;
          right_type text;
        BEGIN
          PERFORM pg_advisory_xact_lock(hashtextextended(NEW.quest_id, 0));
          SELECT quest_id, node_type INTO left_quest, left_type
            FROM research_graph_nodes WHERE node_id = NEW.node_id;
          SELECT quest_id, node_type INTO right_quest, right_type
            FROM research_graph_nodes WHERE node_id = NEW.dependency_node_id;
          IF left_quest <> NEW.quest_id OR right_quest <> NEW.quest_id
             OR left_type <> right_type OR left_type = 'quest' THEN
            RAISE EXCEPTION 'invalid scientific dependency endpoints';
          END IF;
          IF EXISTS (
            WITH RECURSIVE walk(node_id) AS (
              SELECT NEW.dependency_node_id
              UNION
              SELECT dependency_node_id
              FROM research_graph_dependencies edge
              JOIN walk ON edge.node_id = walk.node_id
              WHERE edge.quest_id = NEW.quest_id
            )
            SELECT 1 FROM walk WHERE node_id = NEW.node_id
          ) THEN
            RAISE EXCEPTION 'scientific dependency cycle';
          END IF;
          RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_research_dependency_cycle
        BEFORE INSERT ON research_graph_dependencies
        FOR EACH ROW EXECUTE FUNCTION aletheia_validate_research_dependency()
        """
    )
    op.execute(
        """
        CREATE FUNCTION aletheia_reject_research_ledger_mutation()
        RETURNS trigger AS $$
        BEGIN
          RAISE EXCEPTION 'research program ledger rows are append-only';
        END;
        $$ LANGUAGE plpgsql
        """
    )
    for table in (
        "research_graph_transitions",
        "research_scientific_families",
        "research_campaign_families",
        "research_graph_dependencies",
        "research_program_questions",
        "research_campaign_runs",
        "research_campaign_experiments",
        "research_data_role_allocations",
        "research_budget_allocations",
    ):
        op.execute(
            f"""
            CREATE TRIGGER trg_{table}_immutable
            BEFORE UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION aletheia_reject_research_ledger_mutation()
            """
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DO $$
        BEGIN
          IF EXISTS (
            SELECT 1 FROM scientific_commands
            WHERE command_type = 'research_graph.mutation'
          ) THEN
            RAISE EXCEPTION
              'cannot downgrade F11-S3 while immutable research graph commands exist; '
              'restore a pre-F11-S3 backup instead';
          END IF;
        END;
        $$
        """
    )
    for table in (
        "research_graph_transitions",
        "research_scientific_families",
        "research_campaign_families",
        "research_graph_dependencies",
        "research_program_questions",
        "research_campaign_runs",
        "research_campaign_experiments",
        "research_data_role_allocations",
        "research_budget_allocations",
    ):
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_immutable ON {table}")
    op.execute("DROP FUNCTION IF EXISTS aletheia_reject_research_ledger_mutation()")
    op.execute(
        "DROP TRIGGER IF EXISTS trg_research_dependency_cycle ON research_graph_dependencies"
    )
    op.execute("DROP FUNCTION IF EXISTS aletheia_validate_research_dependency()")
    op.execute("DROP TRIGGER IF EXISTS trg_research_graph_node_transition ON research_graph_nodes")
    op.execute("DROP FUNCTION IF EXISTS aletheia_enforce_research_graph_node_transition()")
    op.execute("DROP TRIGGER IF EXISTS trg_research_graph_node_shape ON research_graph_nodes")
    op.execute("DROP FUNCTION IF EXISTS aletheia_validate_research_graph_node()")
    op.alter_column(
        "scientific_commands", "run_id", existing_type=sa.VARCHAR(length=32), nullable=False
    )
    op.drop_constraint(
        "fk_hypothesis_attempts_research_family",
        "hypothesis_attempts",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_hypothesis_attempts_research_family_id"), table_name="hypothesis_attempts"
    )
    op.drop_column("hypothesis_attempts", "research_family_id")
    op.drop_constraint(
        "fk_budget_events_research_budget_allocation",
        "budget_events",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_budget_events_research_budget_allocation_id"), table_name="budget_events"
    )
    op.drop_column("budget_events", "research_budget_allocation_id")
    op.drop_index(
        op.f("ix_research_campaign_families_family_id"), table_name="research_campaign_families"
    )
    op.drop_index(
        op.f("ix_research_campaign_families_command_id"), table_name="research_campaign_families"
    )
    op.drop_table("research_campaign_families")
    op.drop_index(
        op.f("ix_research_scientific_families_semantic_sha256"),
        table_name="research_scientific_families",
    )
    op.drop_index(
        op.f("ix_research_scientific_families_quest_id"), table_name="research_scientific_families"
    )
    op.drop_index(
        op.f("ix_research_scientific_families_program_node_id"),
        table_name="research_scientific_families",
    )
    op.drop_index(
        op.f("ix_research_scientific_families_family_key"),
        table_name="research_scientific_families",
    )
    op.drop_index(
        op.f("ix_research_scientific_families_created_by"),
        table_name="research_scientific_families",
    )
    op.drop_index(
        op.f("ix_research_scientific_families_created_at"),
        table_name="research_scientific_families",
    )
    op.drop_index(
        op.f("ix_research_scientific_families_command_id"),
        table_name="research_scientific_families",
    )
    op.drop_table("research_scientific_families")
    op.drop_index(
        op.f("ix_research_program_questions_question_sha256"),
        table_name="research_program_questions",
    )
    op.drop_index(
        op.f("ix_research_program_questions_quest_id"), table_name="research_program_questions"
    )
    op.drop_index(
        op.f("ix_research_program_questions_program_node_id"),
        table_name="research_program_questions",
    )
    op.drop_index(
        op.f("ix_research_program_questions_created_at"), table_name="research_program_questions"
    )
    op.drop_index(
        op.f("ix_research_program_questions_command_id"), table_name="research_program_questions"
    )
    op.drop_table("research_program_questions")
    op.drop_index(
        op.f("ix_research_graph_transitions_to_state"), table_name="research_graph_transitions"
    )
    op.drop_index(
        op.f("ix_research_graph_transitions_principal"), table_name="research_graph_transitions"
    )
    op.drop_index(
        op.f("ix_research_graph_transitions_node_id"), table_name="research_graph_transitions"
    )
    op.drop_index(
        op.f("ix_research_graph_transitions_created_at"), table_name="research_graph_transitions"
    )
    op.drop_index(
        op.f("ix_research_graph_transitions_command_id"), table_name="research_graph_transitions"
    )
    op.drop_table("research_graph_transitions")
    op.drop_index(
        op.f("ix_research_graph_dependencies_quest_id"), table_name="research_graph_dependencies"
    )
    op.drop_index(
        op.f("ix_research_graph_dependencies_node_id"), table_name="research_graph_dependencies"
    )
    op.drop_index(
        op.f("ix_research_graph_dependencies_dependency_node_id"),
        table_name="research_graph_dependencies",
    )
    op.drop_index(
        op.f("ix_research_graph_dependencies_created_at"), table_name="research_graph_dependencies"
    )
    op.drop_index(
        op.f("ix_research_graph_dependencies_command_id"), table_name="research_graph_dependencies"
    )
    op.drop_table("research_graph_dependencies")
    op.drop_index(
        op.f("ix_research_data_role_allocations_scope_node_id"),
        table_name="research_data_role_allocations",
    )
    op.drop_index(
        op.f("ix_research_data_role_allocations_role"), table_name="research_data_role_allocations"
    )
    op.drop_index(
        op.f("ix_research_data_role_allocations_quest_id"),
        table_name="research_data_role_allocations",
    )
    op.drop_index(
        op.f("ix_research_data_role_allocations_data_asset_id"),
        table_name="research_data_role_allocations",
    )
    op.drop_index(
        op.f("ix_research_data_role_allocations_created_at"),
        table_name="research_data_role_allocations",
    )
    op.drop_index(
        op.f("ix_research_data_role_allocations_command_id"),
        table_name="research_data_role_allocations",
    )
    op.drop_table("research_data_role_allocations")
    op.drop_index(op.f("ix_research_campaign_runs_run_id"), table_name="research_campaign_runs")
    op.drop_index(op.f("ix_research_campaign_runs_quest_id"), table_name="research_campaign_runs")
    op.drop_index(op.f("ix_research_campaign_runs_created_at"), table_name="research_campaign_runs")
    op.drop_index(op.f("ix_research_campaign_runs_command_id"), table_name="research_campaign_runs")
    op.drop_index(
        op.f("ix_research_campaign_runs_campaign_node_id"), table_name="research_campaign_runs"
    )
    op.drop_table("research_campaign_runs")
    op.drop_index(
        op.f("ix_research_campaign_experiments_run_id"), table_name="research_campaign_experiments"
    )
    op.drop_index(
        op.f("ix_research_campaign_experiments_quest_id"),
        table_name="research_campaign_experiments",
    )
    op.drop_index(
        op.f("ix_research_campaign_experiments_experiment_id"),
        table_name="research_campaign_experiments",
    )
    op.drop_index(
        op.f("ix_research_campaign_experiments_created_at"),
        table_name="research_campaign_experiments",
    )
    op.drop_index(
        op.f("ix_research_campaign_experiments_command_id"),
        table_name="research_campaign_experiments",
    )
    op.drop_index(
        op.f("ix_research_campaign_experiments_campaign_node_id"),
        table_name="research_campaign_experiments",
    )
    op.drop_table("research_campaign_experiments")
    op.drop_index(
        op.f("ix_research_budget_allocations_scope_node_id"),
        table_name="research_budget_allocations",
    )
    op.drop_index(
        op.f("ix_research_budget_allocations_quest_id"), table_name="research_budget_allocations"
    )
    op.drop_index(
        op.f("ix_research_budget_allocations_parent_allocation_id"),
        table_name="research_budget_allocations",
    )
    op.drop_index(
        op.f("ix_research_budget_allocations_kind"), table_name="research_budget_allocations"
    )
    op.drop_index(
        op.f("ix_research_budget_allocations_created_at"), table_name="research_budget_allocations"
    )
    op.drop_index(
        op.f("ix_research_budget_allocations_command_id"), table_name="research_budget_allocations"
    )
    op.drop_table("research_budget_allocations")
    op.drop_index(op.f("ix_research_graph_nodes_spec_sha256"), table_name="research_graph_nodes")
    op.drop_index("ix_research_graph_nodes_quest_type", table_name="research_graph_nodes")
    op.drop_index(op.f("ix_research_graph_nodes_quest_id"), table_name="research_graph_nodes")
    op.drop_index(op.f("ix_research_graph_nodes_parent_node_id"), table_name="research_graph_nodes")
    op.drop_index(op.f("ix_research_graph_nodes_node_type"), table_name="research_graph_nodes")
    op.drop_index(op.f("ix_research_graph_nodes_current_state"), table_name="research_graph_nodes")
    op.drop_index(op.f("ix_research_graph_nodes_created_by"), table_name="research_graph_nodes")
    op.drop_index(op.f("ix_research_graph_nodes_created_at"), table_name="research_graph_nodes")
    op.drop_table("research_graph_nodes")
    # ### end Alembic commands ###
