"""Migration boundaries for replacing the legacy research control plane."""

from .boundary import (
    DEFAULT_FORBIDDEN_MODULE_PREFIXES,
    DEFAULT_LEGACY_DRIVER_IMPORTERS,
    DEFAULT_REQUIRED_TARGET_PACKAGES,
    DEFAULT_STRICT_FORBIDDEN_MODULE_PREFIXES,
    DEFAULT_STRICT_TARGET_PACKAGES,
    DEFAULT_TARGET_PACKAGES,
    DependencyBoundaryViolation,
    find_dependency_boundary_violations,
    find_legacy_driver_import_violations,
)
from .legacy import (
    LegacyDataClass,
    LegacyDataRole,
    LegacyFreezeRequest,
    LegacyFreezerIdentity,
    LegacyFreezerSourceFile,
    LegacyImportReceipt,
    LegacyObjectRole,
    LegacySnapshotInput,
    LegacySnapshotManifest,
    LegacySnapshotObject,
    build_legacy_import_receipt,
    build_legacy_freezer_identity,
    freeze_legacy_snapshot,
    legacy_exporter_code_sha256,
    verify_legacy_snapshot,
)

__all__ = [
    "DEFAULT_FORBIDDEN_MODULE_PREFIXES",
    "DEFAULT_LEGACY_DRIVER_IMPORTERS",
    "DEFAULT_REQUIRED_TARGET_PACKAGES",
    "DEFAULT_STRICT_FORBIDDEN_MODULE_PREFIXES",
    "DEFAULT_STRICT_TARGET_PACKAGES",
    "DEFAULT_TARGET_PACKAGES",
    "DependencyBoundaryViolation",
    "LegacyDataClass",
    "LegacyDataRole",
    "LegacyFreezeRequest",
    "LegacyFreezerIdentity",
    "LegacyFreezerSourceFile",
    "LegacyImportReceipt",
    "LegacyObjectRole",
    "LegacySnapshotInput",
    "LegacySnapshotManifest",
    "LegacySnapshotObject",
    "build_legacy_import_receipt",
    "build_legacy_freezer_identity",
    "find_dependency_boundary_violations",
    "find_legacy_driver_import_violations",
    "freeze_legacy_snapshot",
    "legacy_exporter_code_sha256",
    "verify_legacy_snapshot",
]
